CC = gcc
CFLAGS = -Wall
TARGET = 20182745
SRCS = 20182745.c
HEADERS = mystdio.h 20182745.h
all: $(TARGET)

$(TARGET): $(SRCS) $(HEADERS)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRCS)

clean:
	rm -f $(TARGET) *.o